services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cruise_net

  ms_reserva:
    build:
      context: .
      dockerfile: app/ms_reserva/Dockerfile
    container_name: ms_reserva
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - cruise_net
    volumes:
      - reservas_data:/app/app/ms_reserva/data
  
  ms_bilhete:
    build:
      context: .
      dockerfile: app/ms_bilhete/Dockerfile
    container_name: ms_bilhete
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - cruise_net
    volumes:
      - reservas_data:/app/app/ms_reserva/data
  
  ms_itinerarios:
    build:
      context: .
      dockerfile: app/ms_itinerarios/Dockerfile
    container_name: ms_itinerarios
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - cruise_net
    volumes:
      - reservas_data:/app/app/ms_reserva/data
      - itinerarios_data:/app/app/ms_itinerarios

  ms_itinerarios_api:
    build:
      context: .
      dockerfile: app/api/Dockerfile
      args:
        SERVICE_PATH: app/ms_itinerarios/api
    container_name: ms_itinerarios_api
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - cruise_net
    ports:
      - "5002:5002"
    volumes:
      - reservas_data:/app/app/ms_reserva/data
      - itinerarios_data:/app/app/ms_itinerarios

  ms_pagamento_api:
    build:
      context: .
      dockerfile: app/api/Dockerfile
      args:
        SERVICE_PATH: app/ms_pagamento/api
    container_name: ms_pagamento_api
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - cruise_net
    ports:
      - "5003:5003"

  ms_reserva_api:
    build:
      context: .
      dockerfile: app/api/Dockerfile
      args:
        SERVICE_PATH: app/ms_reserva/api
    container_name: ms_reserva_api
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - cruise_net
    ports:
      - "5001:5001"
    volumes:
      - reservas_data:/app/app/ms_reserva/data
    
  external_payment_service:
    build:
      context: ../external_payment_service
      dockerfile: Dockerfile
    container_name: external_payment_service
    ports:
      - "5050:5050"
    networks:
      - cruise_net

networks:
  cruise_net:
    driver: bridge

volumes:
  reservas_data:
  itinerarios_data:
